# -*- coding: utf-8 -*-
"""Untitled30.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12XOCnwKQEpeBGVh5MkQBOk9nojKtsLc5
"""

#Desarrolla un programa en Python que implemente un sistema de gestión de
#pacientes de una clínica, donde todo el comportamiento se organice mediante
#funciones bien definidas. El programa debe incluir un menú interactivo, validaciones
#de entrada, operaciones lógicas (decisiones y comparaciones) y uso de funciones
#separadas

lista_pacientes=[]

def validar_nombre(nombre):
  return nombre.strip() !=""

def validar_edad(edad):
  return edad.isdigit () and int (edad) >0

def validar_temperatura (temperatura):
  try:
    return 35.0 <= float (temperatura) <=42.0
  except ValueError:
    return False

def agregar_paciente(lista):
  nombre=input("ingrese nombre del paciente: ")
  edad=input("ingrese edad del paciente: ")
  temperatura=input("ingrese temperatura del paciente, debe ser entre 35 y 42 grados: ")

  if validar_nombre(nombre) and validar_edad (edad) and validar_temperatura (temperatura):
    paciente= {
        "nombre": nombre,
        "edad": edad,
        "temperatura": float(temperatura),
        "atendido": False
    }
    lista.append (paciente)
    print("paciente se ha agregado correctamente ")
    return True

  elif not validar_nombre(nombre):
    print(" el nombre no es válido ")

  elif not validar_edad(edad):
    print(" la edad debe ser un numero mayor a cero ")

  elif not validar_temperatura(temperatura):
    print("la temperatura debe ser entre 35 y 42 grados")
    return False

def buscar_paciente(lista, nombre_paciente):
  for i in range (len(lista)):
    if lista [i] ["nombre"]== nombre_paciente:
      return i

  return -1

def eliminar_paciente(lista, nombre_paciente):
  indice= buscar_paciente(lista, nombre_paciente)

  if indice != -1:
    del lista [indice]
    print("paciente eliminado correctamente ")
  else:
    print(f" el paciente '{nombre_paciente}' no se encuentra registrado")

def actualizar_estado(lista):
  for paciente in lista:
    if paciente ["temperatura"] >=37:
      paciente ["atendido"]= True

  return

def mostrar_pacientes():
  if len (lista_pacientes)==0:
    print("no hay pacientes registrados ")
    return

  actualizar_estado (lista_pacientes)
  print(" \n ====lista de pacientes=== \n ")

  for paciente in lista_pacientes:
    print(f"nombre: {paciente['nombre']}")
    print (f"edad: {paciente['edad']}")
    print(f"temperatura: {paciente['temperatura']}")

    if paciente ["atendido"]:
      print("estado: atendido ")

    else:
      print("estado requiere atención")

    print("*******************************")

def mostrar_menu():
  print(" \n ===MENU PRINCIPAL===" )
  print(" 1. Agregar paciente" )
  print(" 2. Buscar paciente" )
  print(" 3. Eliminar paciente" )
  print(" 4. Actualizar estado" )
  print(" 5. mostrar pacientes " )
  print(" 6. salir ")

def leer_opcion():

  while True:

    try:
      opcion=int(input("ingrese opcion del menú del 1 al 6 : "))

      if 1 <= opcion <=6:
        return opcion
      print("ingrese una opcion válida " )
    except ValueError:
      print("debe ingresar un numero valido " )

while True:
  mostrar_menu()
  opcion=leer_opcion()

  if opcion==1:
    agregar_paciente(lista_pacientes)
  elif opcion==2:
    nombre=input("ingrese nombre del paciente a buscar: ")
    indice=buscar_paciente(lista_pacientes, nombre)
    if indice != -1:
      paciente=lista_pacientes[indice]

      print("\n paciente encontrado: ")
      print(f"indice: {indice}")
      print(f"nombre: {paciente['nombre']}")
      print(f"edad: {paciente['edad']}")
      print(f"temperatura: {paciente['temperatura']}")
    else:
      print("paciente no encontrado")

  elif opcion==3:
    nombre=input("ingrese nombre del paciente a eliminar: ")
    eliminar_paciente(lista_pacientes, nombre)

  elif opcion==4:
    actualizar_estado(lista_pacientes)
    print("estado actualizado correctamente ")

  elif opcion==5:
    mostrar_pacientes()

  elif opcion==6:
    print("programa finalizado ")
    break